name: Workflow for the project
on: workflow_dispatch
jobs:
  Testing:
     runs-on: ubuntu:latest
     steps:
        - name: Testing the workflow
          run: echo "THis is just for testing the project thats it "
        
